
services:

  web:
    image: hydropic/visual_fire_inspection_tool_backend:v1.2
    container_name: fastapiwork1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - app-network
    restart: always
    volumes:
    - ./frontend/public:/code/frontend/public
    - ./backend:/code/backend
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]


  mongo:
    container_name: mongowork1
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    networks:
      - app-network

  frontend:
    image: hydropic/visual_fire_inspection_tool_frontend:v1.2
    container_name: frontendwork1
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    restart: always
    volumes:
      - ./frontend/public:/code/public
      - ./frontend/src:/code/src
    environment:
      - VITE_BACKEND_IP=http://127.0.0.1:8000

networks:
  cvat_cvat:
    external: true
  app-network:
    driver: bridge